### ISSUE TITLE
Logout button isn't working.

### ISSUE THREAD

**Issue by czmatejt9** [DislikesSchool/EduPage2#52]
**Describe the bug**
Logout button isnt doing anything.

**To Reproduce**
Click the symbol left to your name on the homapage and then in the drawer click logout - nothing happens.

**Expected behavior**
User should be logged out

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 11
 - OS: Android 12
 - Version: 1.4.0

**Comment by vyPal** [comment]
Issue fixed in 1.4.1
